# Generated by Django 5.0.4 on 2024-04-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Venue Name')),
                ('address', models.CharField(max_length=300)),
                ('zipcode', models.CharField(max_length=10, verbose_name='Zip Code')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('web', models.URLField(blank=True, verbose_name='Website URL')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('owner', models.IntegerField(default=0, verbose_name='Venue Owner')),
                ('venue_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
