# Generated by Django 5.0.4 on 2024-04-16 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Art', '0003_mymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='artwork',
        ),
    ]
