# Generated by Django 5.0.4 on 2024-04-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Art', '0005_item_bid_artwork_biddinghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
